name: "Infra: Tag"
on:
  workflow_dispatch:

  pull_request:
    branches:
      - sainsburys
    types:
      - closed

jobs:
  tag:
    if: ${{ (github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch') }}
    runs-on:
      - self-hosted
      - build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: sainsburys
      - name: default_branch - Create an incremental release
        if: ${{ github.event.repository.default_branch == env.REF }}
        run: |
          git config --global user.email "made@sainsburys.co.uk"
          git config --global user.name "Increment tag"
          echo "Updating repository tags..."
          git fetch origin --tags --quiet
          TAG=`git rev-list --tags="v*" --max-count=1`
          echo "Get last tag: ${TAG}"
          NEXT_TAG="v1.0.0";
          LAST_TAG="empty"
          if [ ! -z "${TAG}" ]; then LAST_TAG=`git describe --tags --match "v*" $(git rev-list --tags="v*" --max-count=1)`; NEXT_TAG="${LAST_TAG%.*}.$((${LAST_TAG##*.}+1))"; fi
          echo "Last tag: ${LAST_TAG}";
          echo "Next tag: ${NEXT_TAG}";
          git tag -a ${NEXT_TAG} -m "Bump version ${LAST_TAG}" -f
          git push --tags -f
